const enums = {
  ROW: "row",
  ROW_REVERSE: "row-reverse",
  COLUMN: "column",
  LEFT: "left",
  RIGHT: "right",
  JUSTIFY: "justify",
  CENTER: "center",
  START: "flex-start",
  END: "flex-end",
  SPACE_A: "space-around",
  SPACE_B: "space-between",
  SPACE_E: "space-evenly",
  ABSOLUTE: "absolute",
  RELATIVE: "relative",
  WRAP: "wrap",
  CAPITALIZE: "capitalize",
  BOLD: "bold",
  ITALIC: "italic",
  NORMAL: "normal",
  PADDING: "padding",
  STRETCH: "stretch",
  CONTAIN: "contain",
  COVER: "cover",
  REPEAT: "repeat",
  LARGE: "large",
  HIDDEN: "hidden",
  HEIGHT: "height",
  IOS: "ios",
  ALWAYS: "always",
  TRANSPARENT: "transparent",
};

export default enums;
